#!/bin/sh

# Run from project root directory
cd "$(dirname "$0")/.." || exit

echo "Updating Arca CLI command completions..."
./scripts/completions/generate.ex

echo "Done! Completions have been updated."
echo "To use tab completion in the REPL, make sure to run './scripts/repl'"